version: "3"
services:
  auth:
    build:
      context: .
    image: "fikridulumina/auth-services:dev-1.0.0"
    container_name: app_auth
    ports:
      - "${APP_PORT}:${APP_PORT}"
    volumes:
      - "./.env/:/opt/app/.env"
      - "./index.js/:/opt/app/index.js"
    depends_on:
      - dbAuth
    networks:
      - auth
    restart: always
    command: sh -c "node index.js"

  dbAuth:
    image: "mysql:5.7"
    container_name: db_auth
    restart: always
    environment:
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASS}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASS}"
    ports:
      - "${DB_PORT}"
    volumes:
      - "./my-db:/var/lib/mysql"
    networks:
      - auth
  dbAuthPma:
    depends_on:
      - dbAuth
    image: phpmyadmin/phpmyadmin
    container_name: dbAuthPma
    restart: always
    ports:
      - "3032:80"
    environment:
      PMA_HOST: dbAuth
    networks:
      - auth

networks:
  auth: null
